using Microsoft.EntityFrameworkCore;
using PTimeJobs.Application.Common.Interfaces;
using PTimeJobs.Domain.Accommodation;
using PTimeJobs.Domain.Analytics;
using PTimeJobs.Domain.Billing;
using PTimeJobs.Domain.Complaints;
using PTimeJobs.Domain.Employers;
using PTimeJobs.Domain.Food;
using PTimeJobs.Domain.Jobs;
using PTimeJobs.Domain.Locations;
using PTimeJobs.Domain.Messaging;
using PTimeJobs.Domain.Notifications;
using PTimeJobs.Domain.Reports;
using PTimeJobs.Domain.Reviews;
using PTimeJobs.Domain.Users;
using PTimeJobs.Domain.Workers;

namespace PTimeJobs.Infrastructure.Persistence;

public sealed class ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
    : DbContext(options), IApplicationDbContext
{
    public DbSet<User> Users => Set<User>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<UserProfile> UserProfiles => Set<UserProfile>();
    public DbSet<UserSession> UserSessions => Set<UserSession>();
    public DbSet<Verification> Verifications => Set<Verification>();
    public DbSet<Country> Countries => Set<Country>();
    public DbSet<State> States => Set<State>();
    public DbSet<City> Cities => Set<City>();
    public DbSet<Area> Areas => Set<Area>();
    public DbSet<Location> Locations => Set<Location>();
    public DbSet<Skill> Skills => Set<Skill>();
    public DbSet<EmployerProfile> EmployerProfiles => Set<EmployerProfile>();
    public DbSet<WorkerProfile> WorkerProfiles => Set<WorkerProfile>();
    public DbSet<WorkerSkill> WorkerSkills => Set<WorkerSkill>();
    public DbSet<WorkerExperience> WorkerExperiences => Set<WorkerExperience>();
    public DbSet<WorkerEducation> WorkerEducations => Set<WorkerEducation>();
    public DbSet<WorkerDocument> WorkerDocuments => Set<WorkerDocument>();
    public DbSet<WorkerAvailability> WorkerAvailabilities => Set<WorkerAvailability>();
    public DbSet<JobCategory> JobCategories => Set<JobCategory>();
    public DbSet<Job> Jobs => Set<Job>();
    public DbSet<JobLocation> JobLocations => Set<JobLocation>();
    public DbSet<JobSchedule> JobSchedules => Set<JobSchedule>();
    public DbSet<JobSkill> JobSkills => Set<JobSkill>();
    public DbSet<JobApplication> JobApplications => Set<JobApplication>();
    public DbSet<HiringStatusHistory> HiringStatusHistories => Set<HiringStatusHistory>();
    public DbSet<MatchingScore> MatchingScores => Set<MatchingScore>();
    public DbSet<Conversation> Conversations => Set<Conversation>();
    public DbSet<ConversationParticipant> ConversationParticipants => Set<ConversationParticipant>();
    public DbSet<Message> Messages => Set<Message>();
    public DbSet<MessageAttachment> MessageAttachments => Set<MessageAttachment>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public DbSet<Notification> Notifications => Set<Notification>();
    public DbSet<Review> Reviews => Set<Review>();
    public DbSet<Complaint> Complaints => Set<Complaint>();
    public DbSet<Report> Reports => Set<Report>();
    public DbSet<Shortlist> Shortlists => Set<Shortlist>();
    public DbSet<FoodProvider> FoodProviders => Set<FoodProvider>();
    public DbSet<FoodItem> FoodItems => Set<FoodItem>();
    public DbSet<FoodPlan> FoodPlans => Set<FoodPlan>();
    public DbSet<FoodPlanItem> FoodPlanItems => Set<FoodPlanItem>();
    public DbSet<FoodSubscription> FoodSubscriptions => Set<FoodSubscription>();
    public DbSet<DeliveryArea> DeliveryAreas => Set<DeliveryArea>();
    public DbSet<AccommodationProvider> AccommodationProviders => Set<AccommodationProvider>();
    public DbSet<Property> Properties => Set<Property>();
    public DbSet<PropertyFacility> PropertyFacilities => Set<PropertyFacility>();
    public DbSet<PropertyImage> PropertyImages => Set<PropertyImage>();
    public DbSet<Facility> Facilities => Set<Facility>();
    public DbSet<RoomType> RoomTypes => Set<RoomType>();
    public DbSet<Room> Rooms => Set<Room>();
    public DbSet<RoomAvailability> RoomAvailabilities => Set<RoomAvailability>();
    public DbSet<AccommodationBooking> AccommodationBookings => Set<AccommodationBooking>();
    public DbSet<Contract> Contracts => Set<Contract>();
    public DbSet<BillingSubscription> BillingSubscriptions => Set<BillingSubscription>();
    public DbSet<Invoice> Invoices => Set<Invoice>();
    public DbSet<Payment> Payments => Set<Payment>();
    public DbSet<Transaction> Transactions => Set<Transaction>();
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public DbSet<AnalyticsEvent> AnalyticsEvents => Set<AnalyticsEvent>();
    public DbSet<UserBehaviorEvent> UserBehaviorEvents => Set<UserBehaviorEvent>();
    public DbSet<SearchHistory> SearchHistories => Set<SearchHistory>();
    public DbSet<RecommendationHistory> RecommendationHistories => Set<RecommendationHistory>();
    public DbSet<UserPreference> UserPreferences => Set<UserPreference>();

    IQueryable<User> IApplicationDbContext.Users => Users;
    IQueryable<Role> IApplicationDbContext.Roles => Roles;
    IQueryable<UserRole> IApplicationDbContext.UserRoles => UserRoles;
    IQueryable<UserProfile> IApplicationDbContext.UserProfiles => UserProfiles;
    IQueryable<UserSession> IApplicationDbContext.UserSessions => UserSessions;
    IQueryable<Verification> IApplicationDbContext.Verifications => Verifications;
    IQueryable<Country> IApplicationDbContext.Countries => Countries;
    IQueryable<State> IApplicationDbContext.States => States;
    IQueryable<City> IApplicationDbContext.Cities => Cities;
    IQueryable<Area> IApplicationDbContext.Areas => Areas;
    IQueryable<Location> IApplicationDbContext.Locations => Locations;
    IQueryable<Skill> IApplicationDbContext.Skills => Skills;
    IQueryable<EmployerProfile> IApplicationDbContext.EmployerProfiles => EmployerProfiles;
    IQueryable<WorkerProfile> IApplicationDbContext.WorkerProfiles => WorkerProfiles;
    IQueryable<WorkerSkill> IApplicationDbContext.WorkerSkills => WorkerSkills;
    IQueryable<WorkerExperience> IApplicationDbContext.WorkerExperiences => WorkerExperiences;
    IQueryable<WorkerEducation> IApplicationDbContext.WorkerEducations => WorkerEducations;
    IQueryable<WorkerDocument> IApplicationDbContext.WorkerDocuments => WorkerDocuments;
    IQueryable<WorkerAvailability> IApplicationDbContext.WorkerAvailabilities => WorkerAvailabilities;
    IQueryable<JobCategory> IApplicationDbContext.JobCategories => JobCategories;
    IQueryable<Job> IApplicationDbContext.Jobs => Jobs;
    IQueryable<JobLocation> IApplicationDbContext.JobLocations => JobLocations;
    IQueryable<JobSchedule> IApplicationDbContext.JobSchedules => JobSchedules;
    IQueryable<JobSkill> IApplicationDbContext.JobSkills => JobSkills;
    IQueryable<JobApplication> IApplicationDbContext.JobApplications => JobApplications;
    IQueryable<HiringStatusHistory> IApplicationDbContext.HiringStatusHistories => HiringStatusHistories;
    IQueryable<MatchingScore> IApplicationDbContext.MatchingScores => MatchingScores;
    IQueryable<Conversation> IApplicationDbContext.Conversations => Conversations;
    IQueryable<ConversationParticipant> IApplicationDbContext.ConversationParticipants => ConversationParticipants;
    IQueryable<Message> IApplicationDbContext.Messages => Messages;
    IQueryable<MessageAttachment> IApplicationDbContext.MessageAttachments => MessageAttachments;
    IQueryable<Permission> IApplicationDbContext.Permissions => Permissions;
    IQueryable<RolePermission> IApplicationDbContext.RolePermissions => RolePermissions;
    IQueryable<Notification> IApplicationDbContext.Notifications => Notifications;
    IQueryable<Review> IApplicationDbContext.Reviews => Reviews;
    IQueryable<Complaint> IApplicationDbContext.Complaints => Complaints;
    IQueryable<Report> IApplicationDbContext.Reports => Reports;
    IQueryable<Shortlist> IApplicationDbContext.Shortlists => Shortlists;
    IQueryable<FoodProvider> IApplicationDbContext.FoodProviders => FoodProviders;
    IQueryable<FoodItem> IApplicationDbContext.FoodItems => FoodItems;
    IQueryable<FoodPlan> IApplicationDbContext.FoodPlans => FoodPlans;
    IQueryable<FoodPlanItem> IApplicationDbContext.FoodPlanItems => FoodPlanItems;
    IQueryable<FoodSubscription> IApplicationDbContext.FoodSubscriptions => FoodSubscriptions;
    IQueryable<DeliveryArea> IApplicationDbContext.DeliveryAreas => DeliveryAreas;
    IQueryable<AccommodationProvider> IApplicationDbContext.AccommodationProviders => AccommodationProviders;
    IQueryable<Property> IApplicationDbContext.Properties => Properties;
    IQueryable<PropertyFacility> IApplicationDbContext.PropertyFacilities => PropertyFacilities;
    IQueryable<PropertyImage> IApplicationDbContext.PropertyImages => PropertyImages;
    IQueryable<Facility> IApplicationDbContext.Facilities => Facilities;
    IQueryable<RoomType> IApplicationDbContext.RoomTypes => RoomTypes;
    IQueryable<Room> IApplicationDbContext.Rooms => Rooms;
    IQueryable<RoomAvailability> IApplicationDbContext.RoomAvailabilities => RoomAvailabilities;
    IQueryable<AccommodationBooking> IApplicationDbContext.AccommodationBookings => AccommodationBookings;
    IQueryable<Contract> IApplicationDbContext.Contracts => Contracts;
    IQueryable<BillingSubscription> IApplicationDbContext.BillingSubscriptions => BillingSubscriptions;
    IQueryable<Invoice> IApplicationDbContext.Invoices => Invoices;
    IQueryable<Payment> IApplicationDbContext.Payments => Payments;
    IQueryable<Transaction> IApplicationDbContext.Transactions => Transactions;
    IQueryable<AuditLog> IApplicationDbContext.AuditLogs => AuditLogs;
    IQueryable<AnalyticsEvent> IApplicationDbContext.AnalyticsEvents => AnalyticsEvents;
    IQueryable<UserBehaviorEvent> IApplicationDbContext.UserBehaviorEvents => UserBehaviorEvents;
    IQueryable<SearchHistory> IApplicationDbContext.SearchHistories => SearchHistories;
    IQueryable<RecommendationHistory> IApplicationDbContext.RecommendationHistories => RecommendationHistories;
    IQueryable<UserPreference> IApplicationDbContext.UserPreferences => UserPreferences;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresEnum<AccountStatus>();
        modelBuilder.HasPostgresEnum<SessionStatus>();
        modelBuilder.HasPostgresEnum<VerificationChannel>();
        modelBuilder.HasPostgresEnum<VerificationStatus>();
        modelBuilder.HasPostgresEnum<EmploymentType>();
        modelBuilder.HasPostgresEnum<SalaryModel>();
        modelBuilder.HasPostgresEnum<JobStatus>();
        modelBuilder.HasPostgresEnum<ApplicationStatus>();
        modelBuilder.HasPostgresEnum<ConversationType>();
        modelBuilder.HasPostgresEnum<NotificationStatus>();
        modelBuilder.HasPostgresEnum<ReviewStatus>();
        modelBuilder.HasPostgresEnum<ComplaintStatus>();
        modelBuilder.HasPostgresEnum<SubscriptionStatus>();
        modelBuilder.HasPostgresEnum<PaymentStatus>();
        modelBuilder.HasPostgresEnum<BookingStatus>();
        modelBuilder.HasPostgresEnum<ContractStatus>();

        modelBuilder.ApplyConfigurationsFromAssembly(typeof(ApplicationDbContext).Assembly);
        base.OnModelCreating(modelBuilder);
    }
}
